msg: welcome to config server
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect      
server:
  error:
    whitelabel:
      enabled: true